/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Canvas;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author john
 */
public class VistaTablero extends javax.swing.JFrame {

    private Controlador controlador;
    private  final Modelo modelo;
    

    public VistaTablero(Modelo aThis) {
        
        this.modelo = aThis;
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JLabel();
        botonPlantar = new javax.swing.JButton();
        botonPedir = new javax.swing.JButton();
        lienzo = new java.awt.Canvas();
        puntuacion = new javax.swing.JLabel();
        mensajeEnemigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensaje.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        mensaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 500, 40));

        botonPlantar.setText("PLANTARSE");
        getContentPane().add(botonPlantar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, -1, -1));

        botonPedir.setText("PEDIR");
        getContentPane().add(botonPedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, -1, -1));

        lienzo.setBackground(new java.awt.Color(23, 133, 1));
        getContentPane().add(lienzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 490));
        getContentPane().add(puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 190, 40));
        getContentPane().add(mensajeEnemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    public void establecerEventos(){
        getBotonPedir().addActionListener(new Controlador(this));
        getBotonPlantar().addActionListener(new Controlador(this));
    }

    public JButton getBotonPedir() {
        return botonPedir;
    }

    public void setBotonPedir(JButton botonPedir) {
        this.botonPedir = botonPedir;
    }

    public JButton getBotonPlantar() {
        return botonPlantar;
    }

    public void setBotonPlantar(JButton botonPlantar) {
        this.botonPlantar = botonPlantar;
    }

    public JLabel getMensaje() {
        return mensaje;
    }

    public void setMensaje(JLabel mensaje) {
        this.mensaje = mensaje;
    }

    public Canvas getLienzo() {
        return lienzo;
    }

    public Modelo getModelo() {
        return modelo;
    }

    public Controlador getControlador() {
        return controlador;
    }

    public JLabel getMensajeEnemigo() {
        return mensajeEnemigo;
    }

    public void setMensajeEnemigo(JLabel mensajeEnemigo) {
        this.mensajeEnemigo = mensajeEnemigo;
    }

    public JLabel getPuntuacion() {
        return puntuacion;
    }

    public void setPuntuacion(JLabel puntuacion) {
        this.puntuacion = puntuacion;
    }
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPedir;
    private javax.swing.JButton botonPlantar;
    private java.awt.Canvas lienzo;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensajeEnemigo;
    private javax.swing.JLabel puntuacion;
    // End of variables declaration//GEN-END:variables
}
