/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Canvas;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author john
 */
public class VistaTablero extends javax.swing.JFrame {

    private  Modelo modelo;
    private Controlador controlador;

    public VistaTablero(Modelo modelo) {
        this.modelo = modelo;
    }

    
    /**
     * Creates new form VistaTablero
     */
    public VistaTablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JLabel();
        botonPlantar = new javax.swing.JButton();
        botonPedir = new javax.swing.JButton();
        lienzo = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensaje.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        mensaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 710, 40));

        botonPlantar.setText("PLANTARSE");
        getContentPane().add(botonPlantar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, -1));

        botonPedir.setText("PEDIR");
        getContentPane().add(botonPedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, -1, -1));

        lienzo.setBackground(new java.awt.Color(23, 133, 1));
        getContentPane().add(lienzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 900, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTablero().setVisible(true);
            }
        });
    }

    public JButton getBotonPedir() {
        return botonPedir;
    }

    public void setBotonPedir(JButton botonPedir) {
        this.botonPedir = botonPedir;
    }

    public JButton getBotonPlantar() {
        return botonPlantar;
    }

    public void setBotonPlantar(JButton botonPlantar) {
        this.botonPlantar = botonPlantar;
    }

    public JLabel getMensaje() {
        return mensaje;
    }

    public void setMensaje(JLabel mensaje) {
        this.mensaje = mensaje;
    }

    public Canvas getLienzo() {
        return lienzo;
    }

    public Modelo getModelo() {
        return modelo;
    }

    public Controlador getControlador() {
        if(controlador==null){
            controlador= new Controlador();
        }
        return controlador;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPedir;
    private javax.swing.JButton botonPlantar;
    private java.awt.Canvas lienzo;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
